# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180927_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(max_length=144),
        ),
    ]
